### ISSUE TITLE
Hiperlink not working for BitBucket

### ISSUE THREAD

**Issue by Ricard** [AlanWalk/markdown-toc#11]
Thanks for your collaboration with open source.

This plugin is not adding <a href=""></a> to each title of document.
Therefore, links on ToC does not work in BitBucket (it does for GitHub).

I had no time to look for the reason, but I have to say that this one is working great: https://github.com/joffreykern/vscode-markdown-toc

**Comment by AlanWalk** [comment]
Hi, I'm sorry for this reply that is so slow. Default setting is generate anchor for github. You can reset "markdown-toc.anchorMode" from "github.com" to "bitbucket.org".

**Comment by AlanWalk** [comment]
![file_work](https://cloud.githubusercontent.com/assets/4654826/21973744/d2e7c07c-dbfd-11e6-8071-8a6166dcc892.png)
![image](https://cloud.githubusercontent.com/assets/4654826/21973749/deceb468-dbfd-11e6-8c65-db5f30b2c2fd.png)
You can choose one by yourself.
