### ISSUE TITLE
Anchor for Chinese characters

### ISSUE THREAD

**Issue by flinhong** [AlanWalk/markdown-toc#13]
It seems that Chinese characters (or other characters other than English) in headings will convert into UTF-8 code like `%AF%B9%E8` in the URL part. Thus cannot be used as anchors in vscode preview mode.

Maybe something like `force_encoding('utf-8')` can fix this.

**Comment by AlanWalk** [comment]
最近有点忙，刚提的1.4.4版本解决了这个问题，更新一下试试

**Comment by flinhong** [comment]
🤗赞一个
