### ISSUE TITLE
The right-mouse menu need to change!

### ISSUE THREAD

**Issue by zroiiiorz** [AlanWalk/markdown-toc#16]
I hope it just working on markdown files! But I can see the right-mouse menu in anywhere when i click  the right mouse button。

**Comment by AlanWalk** [comment]
Thank you for your advice.

**Comment by junian** [comment]
I made pullrequest #17 to fix this.

**Comment by AlanWalk** [comment]
Hi, Version 1.5.2 is released. You can update it.
