### ISSUE TITLE
wrong section number 

### ISSUE THREAD

**Issue by Hunter-Yi** [AlanWalk/markdown-toc#28]
Details are shown in the picture
![default](https://user-images.githubusercontent.com/15889247/27728188-e10bab72-5db3-11e7-95a4-8af1e470d12d.png)

please look at [1.1.3.3] & [1.2.1.4], [1.2.1.1] ~ [1.2.1.3] are skiped, but [1.2.2.1] is not,
i try to [Markdown Sections : Delete] and other three command , reproduce again;
all of above can work properly one hour ago;
OS : ubuntu desktop 16.04
vscode : 1.13.1
Markdown-TOC : 1.5.5

**Comment by AlanWalk** [comment]
不好意思，最近有点忙，我已经修复了这个问题，这两天应该会发布1.5.6版本，到时候更新下应该就没问题了。

**Comment by Hunter-Yi** [comment]
还以为你是歪果仁,我还特意用英语写的,尴尬.
期待新版本
