### ISSUE TITLE
TOC created with tab indent

### ISSUE THREAD

**Issue by gnhuy91** [AlanWalk/Markdown-TOC#3]
Currently it creates a code block (due to tab indent):

	- [Table of Contents](#table-of-contents)
	- [Jenkins Pipeline](#jenkins-pipeline)
	- [AWS EC2](#aws-ec2)
	- [MySQL container](#mysql-container)

```
<!-- TOC -->

	- [Table of Contents](#table-of-contents)
	- [Jenkins Pipeline](#jenkins-pipeline)
	- [AWS EC2](#aws-ec2)
	- [MySQL container](#mysql-container)

<!-- /TOC -->
```

Instead of:
- [Table of Contents](#table-of-contents)
- [Jenkins Pipeline](#jenkins-pipeline)
- [AWS EC2](#aws-ec2)
- [MySQL container](#mysql-container)

**Comment by AlanWalk** [comment]
I will fix it as soon as possible, thank you!

**Comment by AlanWalk** [comment]
Do you want to add tab indent for your toc list?

**Comment by gnhuy91** [comment]
Nope, toc list should not be indented at all.

**Comment by gnhuy91** [comment]
Oh, of course except for nested items, which can be either 4 spaces/1 tab i think. Just the initial tab indent that force the TOC to be rendered as code block instead of actual list items.

**Comment by AlanWalk** [comment]
Hi, I had updated the extension, you can update to latest version.

**Comment by gnhuy91** [comment]
Thanks, it works great!
