### ISSUE TITLE
Is it possible to put TOC to the left panel of window?

### ISSUE THREAD

**Issue by ahui132** [AlanWalk/markdown-toc#40]
This feature will be convenient for navigation while editing markdown.

**Comment by AlanWalk** [comment]
Like this? Next version will have it.

![treeview](https://user-images.githubusercontent.com/4654826/34325320-1a8b0820-e8c9-11e7-85b7-0224c2680c38.png)

**Comment by ahui132** [comment]
@AlanWalk Awesome!
I guess this feature is nothing to do with  the TOC tag (which is at the head of markdown file).
Look forward to the next version!

**Comment by AlanWalk** [comment]
This is a independent feature~

**Comment by AlanWalk** [comment]
Hi, [Markdown Navigation](https://marketplace.visualstudio.com/items?itemName=AlanWalk.markdown-navigation) had upload to markplace, you can download it~

![qq 20180416191208](https://user-images.githubusercontent.com/4654826/38805895-1842412a-41aa-11e8-984d-6e8acc5e5f52.png)

![screenshot](https://user-images.githubusercontent.com/4654826/38805834-e31ccc0e-41a9-11e8-9ed3-ee1b7798ad52.png)
