### ISSUE TITLE
Insert/Update Sections removes digits at the beginning of the titles

### ISSUE THREAD

**Issue by kondratyev-nv** [AlanWalk/markdown-toc#43]
Markdown Sections: Insert/Update and Delete operations do not work correctly on sections that start with digits, even if they are not separated by space from remaining symbols. For example, Insert/Update on markdown file with this sample content

    # 3D surface
    ## 10 ways to do something

results in

    # 1. D surface
    ## 1.1. ways to do something

but 

    # 1. 3D surface
    ## 1.1. 10 ways to do something

is expected.

Delete operation also removes numbers from the title if there is no section numbers (works fine if they are present).

    # D surface
    ## ways to do something with 3D surface

**Comment by AlanWalk** [comment]
Hi, i'm sorry for this bug, i will fix it.
Thank you~

**Comment by kondratyev-nv** [comment]
Thank you! You may see, that I've fixed this issue for the latest stable version in https://github.com/AlanWalk/markdown-toc/pull/44.

**Comment by AlanWalk** [comment]
Thank you, i will merge it~
