### ISSUE TITLE
Option for indentation

### ISSUE THREAD

**Issue by akshaybabloo** [AlanWalk/markdown-toc#47]
Add option for the number of indentations; I think the default is set to 4.

**Comment by Splike** [comment]
Yes please!

I use the markdownlint package, which creates warnings on anything other than2-space indents. They have quite a good explanation here as to why that is: https://github.com/DavidAnson/markdownlint/blob/v0.8.1/doc/Rules.md#md007

The option to choose how many spaces the default indentation is, would be great!

**Comment by AlanWalk** [comment]
@akshaybabloo @Splike 
Hi, you can config it in your settings file.
```
{
    "[markdown]": {
        "editor.tabSize": 2,
        "editor.insertSpaces": true
    }
}
```

**Comment by Splike** [comment]
Thanks @AlanWalk , that solved it for me!

**Comment by akshaybabloo** [comment]
Thanks @AlanWalk
