### ISSUE TITLE
Fails on Scandinavian å character

### ISSUE THREAD

**Issue by askerb** [AlanWalk/markdown-toc#5]
In getHash(), the regexp is missing the 'å' character used in Scandinavian languages. This results in the å character is missing from the links in the TOC.

The existing:
`hash = hash.replace(/[^a-z0-9\u4e00-\u9fa5äüö\-]/g, '');`

Could instead be:
`hash = hash.replace(/[^a-z0-9\u4e00-\u9fa5åäüö\-]/g, '');`

**Comment by AlanWalk** [comment]
I will fix it as soon as possible, thank you!
