### ISSUE TITLE
Identical headers will link to first occurrence in text.

### ISSUE THREAD

**Issue by askerb** [AlanWalk/markdown-toc#6]
If the same header is used several times in a text, all occurrences in the TOC will link to the first occurrence. The example below will produce a TOC which links to "News" in Release 3 for both Release 2 & 3 in the TOC.

```
# Release history for my app
## Release 3
### News
New in this release...

## Release 2
### News
This release introduces...
```

**Comment by AlanWalk** [comment]
I will fix it as soon as possible, thank you!

**Comment by AlanWalk** [comment]
Hi, I'm sorry for this reply that is so slow. I had fix it on new version, you can update to it.
Version: 1.4.6
