### ISSUE TITLE
自动生成的菜单错误

### ISSUE THREAD

**Issue by packmoon** [AlanWalk/markdown-toc#70]
Issue Type: <b>Bug</b>

如下，生成的菜单格式错误。无法link

autoauto- [1. 计划表](#1-计划表)auto    - [1.1. 一期任务](#11-一期任务)auto    - [1.2. 周任务](#12-周任务)auto        - [1.2.1. 第一周:12-01/12-06](#121-第一周12-0112-06)autoauto

Extension version: 1.5.6
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by packmoon** [comment]
> 解决办法：设置中将“默认行尾字符”改为 '\n'
> ref: #65

谢谢

**Comment by vivitrip** [comment]
> 解决办法：设置中将“默认行尾字符”改为 '\n'
> ref: #65

我也遇到了这个问题，用这个方法解决了，感谢
