### ISSUE TITLE
Generated Link not set toLowerCase

### ISSUE THREAD

**Issue by mpolinowski** [AlanWalk/Markdown-TOC#81]
I am not sure which Update changed this behaviour. But before every generated link was in lower case:

```markdown
- [Introduction](#introduction)
# Introduction
```

Now, this is no longer so:

```markdown
- [Introduction](#Introduction)
# Introduction
```

The anchor tags are generated automatically (toLowerCase) in my project - so this change broke all my ToC's.

Is this a bug? Or was it changed as a Feature? Can it be exposed to Addon Settings ?

**Comment by mpolinowski** [comment]
This is really an annoying bug :)

You cannot even override it by hand - I deactivated `update on save` but it still updates the corrected ToC when I save the file.

So the ToC is generated correctly but once I save the file it gets updated:

![toc](https://user-images.githubusercontent.com/18694428/60382953-446c4500-9a9d-11e9-8684-e4faedb09f60.gif)

**Comment by huntertran** [comment]
Hi, could you please open an issue [here](https://github.com/huntertran/markdown-toc/issues)? Thanks

**Comment by mpolinowski** [comment]
Hi,

can someone confirm that the issue was fixed? I just noticed that it was working today and re-saved all my markdown pages. All back to normal for me.

**Comment by mpolinowski** [comment]
Ok, I tested it with a couple of projects and so far it is working again. No idea what changed. But I am closing this issue for now.
