### ISSUE TITLE
Support trailing #

### ISSUE THREAD

**Issue by MarioSchwalbe** [AlanWalk/markdown-toc#9]
Hi,

would it be possible to also support header lines with trailing slashes ([alternate syntax](http://daringfireball.net/projects/markdown/syntax#header))?

I skipped the pull request, because it's just a single line of code in `MarkdownTocTools.prototype.getHeaderList`:
```js
var title = lineText.substr(depth).trim();
title = title.replace(/\#*$/, "").trim();                                                                   
```

Thanks.

**Comment by AlanWalk** [comment]
Thank you for your advice.
